<a href="https://colab.research.google.com/github/nabhllaaa/Prediksi-Performa-Mahasiswa-CSE/blob/main/Data_Cleaning_%26_Preprocessing_Kelompok_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tahap 1 - Memuat Dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = 'model_ready_data CSE Student.csv'
df = pd.read_csv(file_path)

print("✅ Tahap 1: Dataset Berhasil Dimuat")
print("-" * 50)

df.head()

✅ Tahap 1: Dataset Berhasil Dimuat
--------------------------------------------------

,Age,SleepPerDayHours,NumberOfFriend,Gender_Male,AcademicPerformance_Below average,AcademicPerformance_Excellent,AcademicPerformance_Good,TakingNoteInClass_Sometimes,TakingNoteInClass_Yes,DepressionStatus_Sometimes,DepressionStatus_Yes,FaceChallangesToCompleteAcademicTask_Sometimes,FaceChallangesToCompleteAcademicTask_Yes,LikePresentation_Yes,LikeNewThings_Yes
0,23,12,6.0,True,False,False,False,False,False,True,False,False,True,True,True
1,23,8,80.0,True,False,True,False,True,False,False,True,False,False,True,True
2,24,8,10.0,True,False,False,False,False,False,True,False,True,False,False,True
3,20,5,15.0,False,False,False,True,False,True,True,False,False,True,False,True
4,24,5,2.0,False,False,False,False,False,True,False,True,False,True,True,True

In [ ]:
df.isnull().sum()

df = df.dropna()

In [ ]:
numerical_cols = ['Age', 'SleepPerDayHours', 'NumberOfFriend']

Q1 = df[numerical_cols].quantile(0.25)
Q3 = df[numerical_cols].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[numerical_cols] < (Q1 - 1.5 * IQR)) |
          (df[numerical_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [ ]:
df.shape
df.head()

,Age,SleepPerDayHours,NumberOfFriend,Gender_Male,AcademicPerformance_Belowaverage,AcademicPerformance_Excellent,AcademicPerformance_Good,TakingNoteInClass_Sometimes,TakingNoteInClass_Yes,DepressionStatus_Sometimes,DepressionStatus_Yes,FaceChallangesToCompleteAcademicTask_Sometimes,FaceChallangesToCompleteAcademicTask_Yes,LikePresentation_Yes,LikeNewThings_Yes
0,0.311504,3.194790,0.359998,True,False,False,False,False,False,True,False,False,True,True,True
2,0.951819,0.830645,1.613639,True,False,False,False,False,False,True,False,True,False,False,True
4,0.951819,-0.942463,-0.893643,False,False,False,False,False,True,False,True,False,True,True,True
5,0.311504,0.830645,2.240460,True,False,False,True,True,False,True,False,False,False,True,True
6,-0.969125,0.830645,0.673408,False,False,False,True,False,True,False,False,False,False,False,True